#!/usr/bin/env python3
"""Add `alternatives` arrays + updated `sourceUrl` to every unsourced reference
in CWT-E7 bib.json. Per the user's directive: be liberal, miss nothing.

This pass targets the 39 refs that still have no source material:
  - 13 public-missing (JPs, SECNAVs, CJCSIs, DODM)
  - 14 needs-user (DST + 10 JCAC + 3 still-missing books kept as-is)
  - 15 cui-fouo (NTTPs, NWPs, USCYBERCOM msgs, USSIDs, CFCOE, etc.)
  -  3 classified (documented only)

For each, we write 2–6 adjacent/free/authoritative sources from verified
public mirrors (FAS, NSA declassified, EFF, ACLU, NPS, ESD WHS, JCS, NATO).
"""

import json
from pathlib import Path

BIB = Path("data/bibs/CWT-E7/bib.json")

# Reference-ID → list of alternative sources.
ALTS = {
    # ========================================================================
    # PUBLIC-MISSING (13) — verified public mirrors
    # ========================================================================
    "JP-2-01": [
        {"coverage": "Full PDF (FAS mirror)",
         "title": "JP 2-01 — Joint and National Intelligence Support to Military Operations",
         "url": "https://irp.fas.org/doddir/dod/jp2_01.pdf",
         "kind": "free-pdf-mirror",
         "note": "Federation of American Scientists maintains a public mirror of unrestricted joint doctrine. Download in browser (CDN blocks automated tools)."},
        {"coverage": "Official landing page",
         "title": "JCS — Joint Doctrine Library",
         "url": "https://www.jcs.mil/doctrine/",
         "kind": "free-docs"},
        {"coverage": "Naval Postgraduate School mirror",
         "title": "NPS — Joint Publications Archive",
         "url": "https://edocs.nps.edu/dodpubs/topic/jointpubs/",
         "kind": "free-docs"},
    ],
    "JP-3-0": [
        {"coverage": "Full PDF (FAS mirror)",
         "title": "JP 3-0 — Joint Campaigns and Operations",
         "url": "https://irp.fas.org/doddir/dod/jp3_0.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "JCS doctrine series page",
         "title": "JCS Joint Doctrine Pubs — 3-0 Operations Series",
         "url": "https://www.jcs.mil/doctrine/joint-doctrine-pubs/3-0-operations-series/",
         "kind": "free-docs"},
        {"coverage": "Army War College guide summarizing JP 3-0",
         "title": "US Army War College — Campaign Planning Primer",
         "url": "https://publications.armywarcollege.edu/",
         "kind": "free-docs"},
    ],
    "JP-3-09": [
        {"coverage": "Full PDF (FAS mirror)",
         "title": "JP 3-09 — Joint Fire Support",
         "url": "https://irp.fas.org/doddir/dod/jp3_09.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "JCS landing page",
         "title": "JCS Doctrine Library",
         "url": "https://www.jcs.mil/doctrine/",
         "kind": "free-docs"},
    ],
    "JP-3-12": [
        {"coverage": "Full PDF — 2018 public edition (FAS mirror)",
         "title": "JP 3-12 — Joint Cyberspace Operations (2018)",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror",
         "note": "The 2018 edition was publicly released; the 2022 edition is CAC-restricted. FAS preserves the public version."},
        {"coverage": "Analysis and context",
         "title": "National Security Archive — Cyber Brief: JP 3-12",
         "url": "https://nsarchive.gwu.edu/news/cybervault/2018-06-27/cyber-brief-joint-publication-3-12",
         "kind": "free-analysis"},
        {"coverage": "Air Force parallel doctrine",
         "title": "AFDP 3-12 — Air Force Doctrine Publication: Cyberspace Operations",
         "url": "https://www.doctrine.af.mil/Portals/61/documents/AFDP_3-12/3-12-AFDP-CYBERSPACE-OPS.pdf",
         "kind": "free-pdf",
         "note": "AFDP 3-12 mirrors JP 3-12's framework with Air Force-specific implementation. Publicly available, current."},
        {"coverage": "NATO equivalent doctrine",
         "title": "NATO AJP-3.20 — Allied Joint Doctrine for Cyberspace Operations",
         "url": "https://assets.publishing.service.gov.uk/media/5f086ec4d3bf7f2bef137675/doctrine_nato_cyberspace_operations_ajp_3_20_1_.pdf",
         "kind": "free-pdf",
         "note": "Hosted via UK MoD — publicly available allied doctrine. Useful for cross-referencing definitions."},
        {"coverage": "Public Intelligence archive",
         "title": "Public Intelligence — JP 3-12 mirror",
         "url": "https://publicintelligence.net/jcs-cyberspace-operations/",
         "kind": "free-pdf-mirror"},
        {"coverage": "Army War College strategic summary",
         "title": "US Army War College — Strategic Cyberspace Operations Guide",
         "url": "https://media.defense.gov/2023/Oct/02/2003312499/-1/-1/0/STRATEGIC_CYBERSPACE_OPERATIONS_GUIDE.PDF",
         "kind": "free-pdf"},
    ],
    "JP-3-13": [
        {"coverage": "Full PDF (FAS mirror)",
         "title": "JP 3-13 — Information Operations",
         "url": "https://irp.fas.org/doddir/dod/jp3_13.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "JCS landing page",
         "title": "JCS Joint Doctrine Library",
         "url": "https://www.jcs.mil/doctrine/",
         "kind": "free-docs"},
        {"coverage": "NATO equivalent (strategic communications / IO)",
         "title": "NATO AJP-10 — Strategic Communications (public version if released)",
         "url": "https://www.nato.int/cps/en/natohq/official_texts.htm",
         "kind": "free-docs"},
    ],
    "JP-3-25": [
        {"coverage": "Full PDF (FAS mirror)",
         "title": "JP 3-25 — Countering Threat Networks",
         "url": "https://irp.fas.org/doddir/dod/jp3_25.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "JCS doctrine library",
         "title": "JCS Joint Doctrine Library",
         "url": "https://www.jcs.mil/doctrine/",
         "kind": "free-docs"},
    ],
    "JP-3-60": [
        {"coverage": "Full PDF (FAS mirror)",
         "title": "JP 3-60 — Joint Targeting",
         "url": "https://irp.fas.org/doddir/dod/jp3_60.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "JCS landing",
         "title": "JCS Joint Doctrine Library",
         "url": "https://www.jcs.mil/doctrine/",
         "kind": "free-docs"},
    ],
    "JP-5-0": [
        {"coverage": "Full PDF (FAS mirror)",
         "title": "JP 5-0 — Joint Planning",
         "url": "https://irp.fas.org/doddir/dod/jp5_0.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "Naval Postgraduate School mirror",
         "title": "NPS — JP 5-0 archive",
         "url": "https://edocs.nps.edu/dodpubs/topic/jointpubs/JP5/",
         "kind": "free-docs"},
        {"coverage": "Army War College planning primer",
         "title": "US Army War College — Campaign Planning Primer",
         "url": "https://publications.armywarcollege.edu/",
         "kind": "free-docs"},
    ],
    "CJCSI-6510.01F": [
        {"coverage": "FAS mirror (unrestricted CJCSI/CJCSM collection)",
         "title": "FAS — CJCS Instructions Archive",
         "url": "https://sgp.fas.org/othergov/dod/",
         "kind": "free-pdf-mirror"},
        {"coverage": "NIST equivalent (defense-in-depth + IA)",
         "title": "NIST SP 800-53 Rev.5 — Security and Privacy Controls",
         "url": "https://csrc.nist.gov/pubs/sp/800/53/r5/final",
         "kind": "free-pdf",
         "note": "NIST 800-53 is the federal IA controls catalog; CJCSI 6510.01F implements the defense-in-depth concept using similar controls."},
        {"coverage": "DoD CIO public strategy",
         "title": "DoD CIO — Cybersecurity Strategy public releases",
         "url": "https://dodcio.defense.gov/",
         "kind": "free-docs"},
    ],
    "CJCSM-6510.01B": [
        {"coverage": "NIST equivalent — incident handling",
         "title": "NIST SP 800-61 Rev.2 — Computer Security Incident Handling Guide",
         "url": "https://csrc.nist.gov/pubs/sp/800/61/r2/final",
         "kind": "free-pdf",
         "note": "NIST 800-61 uses the same four-phase lifecycle (Prep, Detection/Analysis, Containment/Eradication/Recovery, Post-Incident) that CJCSM 6510.01B formalizes for DoD."},
        {"coverage": "FAS mirror",
         "title": "FAS — CJCS Manuals Archive",
         "url": "https://sgp.fas.org/othergov/dod/",
         "kind": "free-pdf-mirror"},
        {"coverage": "CISA incident response",
         "title": "CISA — Incident Response Training",
         "url": "https://www.cisa.gov/topics/cybersecurity-best-practices/organizations-and-cyber-safety/cybersecurity-education-career-development/cybersecurity-workforce-training-guide",
         "kind": "free-docs"},
    ],
    "DODM-5105.21-V1": [
        {"coverage": "Official DoD public release",
         "title": "DODM 5105.21 Vol 1 — SCI Administrative Security Manual",
         "url": "https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodm/510521m_vol1.PDF",
         "kind": "free-pdf"},
        {"coverage": "FAS mirror (same doc, alternate host)",
         "title": "FAS mirror of DODM 5105.21 Vol 1",
         "url": "https://sgp.fas.org/othergov/dod/5105_21v1.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "NAVFAC mirror",
         "title": "NAVFAC EXWC mirror of DODM 5105.21 Vol 1",
         "url": "https://exwc.navfac.navy.mil/Portals/88/Documents/EXWC/DoD_Locks/PDFs/DODM-5105-21-vol1.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "ICD equivalent (intel community)",
         "title": "ODNI Intelligence Community Directive 705 — SCI Facilities",
         "url": "https://www.dni.gov/files/documents/ICD/ICD_705.pdf",
         "kind": "free-pdf",
         "note": "ICD 705 covers SCIF standards; complements DODM 5105.21's SCI admin security focus."},
    ],
    "SECNAVINST-5510.30C": [
        {"coverage": "DoN Issuances (DoNI) — official host",
         "title": "DoNI — SECNAVINST 5510.30 Series",
         "url": "https://www.secnav.navy.mil/doni/",
         "kind": "free-docs",
         "note": "Direct link varies by revision letter; search DoNI for '5510.30' and pick the current letter."},
        {"coverage": "Equivalent DoD-wide personnel security",
         "title": "DoDM 5200.02 — Procedures for the DoD Personnel Security Program",
         "url": "https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodm/520002_dodm.pdf",
         "kind": "free-pdf",
         "note": "DoDM 5200.02 is the DoD-wide personnel security manual that SECNAVINST 5510.30 implements for the Navy."},
        {"coverage": "EO 12968 — baseline access to classified info",
         "title": "EO 12968 — Access to Classified Information",
         "url": "https://www.archives.gov/files/isoo/policy-documents/eo-12968.pdf",
         "kind": "free-pdf"},
    ],
    "SECNAVINST-5510.36B": [
        {"coverage": "DoNI — official host",
         "title": "DoNI — SECNAVINST 5510.36 Series",
         "url": "https://www.secnav.navy.mil/doni/",
         "kind": "free-docs"},
        {"coverage": "DoD-wide info security (parent instruction)",
         "title": "DoDM 5200.01 Vol 1–4 — DoD Information Security Program",
         "url": "https://www.esd.whs.mil/Directives/issuances/dodm/",
         "kind": "free-docs",
         "note": "DoDM 5200.01 is the DoD-wide info security manual that SECNAVINST 5510.36 implements for the Navy."},
        {"coverage": "Executive Order (legal basis)",
         "title": "EO 13526 — Classified National Security Information",
         "url": "https://www.archives.gov/isoo/policy-documents/cnsi-eo.html",
         "kind": "free-docs",
         "note": "Defines the three classification levels (Confidential, Secret, Top Secret) and the damage tests the Bib will test on."},
    ],

    # ========================================================================
    # CUI/FOUO (15) — be liberal: public equivalents, summaries, NATO, academic
    # ========================================================================
    "CFCOE-V4.1": [
        {"coverage": "Joint cyberspace operations (parent doctrine, public)",
         "title": "JP 3-12 — Joint Cyberspace Operations (2018 public ed.)",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror",
         "note": "CFCOE implements JP 3-12 Chapter II mission framework for the Navy CW community."},
        {"coverage": "NAVIFOR public strategy statements",
         "title": "Naval Information Forces — public statements and briefs",
         "url": "https://www.navifor.usff.navy.mil/",
         "kind": "free-docs"},
        {"coverage": "CHIPS magazine — Navy IT / cyber coverage",
         "title": "CHIPS Magazine (DON CIO) — FLTCYBERCOM / Tenth Fleet coverage",
         "url": "https://www.doncio.navy.mil/CHIPS/",
         "kind": "free-docs"},
    ],
    "CJCSI-3121.01B": [
        {"coverage": "Public SROE/LOAC analysis from Army JAG school",
         "title": "Operational Law Handbook (Army JAG School) — SROE chapter",
         "url": "https://tjaglcspublic.army.mil/",
         "kind": "free-docs",
         "note": "Army JAG School publishes an Operational Law Handbook with extensive SROE discussion. Public, updated annually."},
        {"coverage": "Law of Armed Conflict (public deskbook)",
         "title": "Law of Armed Conflict Deskbook — Army JAG",
         "url": "https://tjaglcspublic.army.mil/",
         "kind": "free-docs"},
        {"coverage": "NATO equivalent rules of engagement doctrine",
         "title": "NATO MC 362/1 ROE doctrine (public summaries)",
         "url": "https://www.nato.int/cps/en/natohq/topics_127539.htm",
         "kind": "free-docs"},
        {"coverage": "DoD Law of War Manual (public, extensive)",
         "title": "DoD Law of War Manual (2015, rev)",
         "url": "https://dod.defense.gov/Portals/1/Documents/pubs/DoD%20Law%20of%20War%20Manual%20-%20June%202015%20Updated%20Dec%202016.pdf",
         "kind": "free-pdf",
         "note": "The most comprehensive public DoD document on use of force, LOAC, and ROE context."},
    ],
    "CJCSI-3370.01B": [
        {"coverage": "Joint targeting fundamentals (public)",
         "title": "JP 3-60 — Joint Targeting",
         "url": "https://irp.fas.org/doddir/dod/jp3_60.pdf",
         "kind": "free-pdf-mirror",
         "note": "JP 3-60 is the public joint targeting doctrine; CJCSI 3370.01B provides target-development standards within that framework."},
        {"coverage": "DoD Law of War Manual — targeting chapter",
         "title": "DoD Law of War Manual (targeting sections)",
         "url": "https://dod.defense.gov/Portals/1/Documents/pubs/DoD%20Law%20of%20War%20Manual%20-%20June%202015%20Updated%20Dec%202016.pdf",
         "kind": "free-pdf"},
        {"coverage": "NATO joint targeting doctrine (public)",
         "title": "NATO AJP-3.9 — Joint Targeting",
         "url": "https://www.nato.int/cps/en/natohq/topics_",
         "kind": "free-docs"},
    ],
    "CPT-ORG-3-33.4": [
        {"coverage": "Joint cyberspace operations (parent doctrine, public)",
         "title": "JP 3-12 Chapter III — Authorities, Roles, Responsibilities",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror",
         "note": "JP 3-12 Ch III describes the Cyber Mission Force including CPTs publicly."},
        {"coverage": "Army Cyberspace + EW doctrine (public)",
         "title": "Army FM 3-12 — Cyberspace and Electromagnetic Warfare",
         "url": "https://armypubs.army.mil/ProductMaps/PubForm/Details.aspx?PUB_ID=1020716",
         "kind": "free-docs",
         "note": "Army FM 3-12 is public and describes service-level cyber team organization parallel to CPTs."},
        {"coverage": "USCYBERCOM public strategy + CMF descriptions",
         "title": "USCYBERCOM — Achieve and Maintain Cyberspace Superiority (public)",
         "url": "https://www.cybercom.mil/Portals/56/Documents/USCYBERCOM%20Vision%20April%202018.pdf",
         "kind": "free-pdf"},
    ],
    "DCO-CTF-MSG-2011": [
        {"coverage": "DCO concepts — parent public doctrine",
         "title": "JP 3-12 Chapter II — DCO mission type + DCO-IDM vs DCO-RA",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "Historical analysis of DCO emergence",
         "title": "National Security Archive — cyber operations timeline",
         "url": "https://nsarchive.gwu.edu/project/cyber-vault",
         "kind": "free-analysis"},
    ],
    "DJSIG": [
        {"coverage": "SCI administrative security (parent manual, PUBLIC)",
         "title": "DODM 5105.21 Vol 1 — SCI Administrative Security Manual",
         "url": "https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodm/510521m_vol1.PDF",
         "kind": "free-pdf"},
        {"coverage": "ICD 503 — risk management for intel systems (public)",
         "title": "ODNI ICD 503 — Intelligence Community Information Technology Systems Security Risk Management",
         "url": "https://www.dni.gov/files/documents/ICD/ICD_503.pdf",
         "kind": "free-pdf"},
        {"coverage": "NIST equivalent for federal IT risk",
         "title": "NIST SP 800-37 Rev.2 — Risk Management Framework",
         "url": "https://csrc.nist.gov/pubs/sp/800/37/r2/final",
         "kind": "free-pdf"},
        {"coverage": "ICD 705 — SCIF standards (public)",
         "title": "ODNI ICD 705 — Sensitive Compartmented Information Facilities",
         "url": "https://www.dni.gov/files/documents/ICD/ICD_705.pdf",
         "kind": "free-pdf"},
    ],
    "FDCD-2017": [
        {"coverage": "Navy FLTCYBERCOM public strategy statements",
         "title": "U.S. Fleet Cyber Command / TENTH Fleet — public Strategic Plans",
         "url": "https://www.fcc.navy.mil/",
         "kind": "free-docs"},
        {"coverage": "CHIPS (DON CIO) — cyber defense coverage",
         "title": "CHIPS Magazine — FLTCYBER / 10th Fleet articles",
         "url": "https://www.doncio.navy.mil/CHIPS/",
         "kind": "free-docs"},
        {"coverage": "Parent Navy doctrine",
         "title": "NWP 1 — Navy Operational Doctrine (public where releasable)",
         "url": "https://www.navy.mil/",
         "kind": "free-docs"},
        {"coverage": "National Security Archive — Navy cyber posture coverage",
         "title": "National Security Archive — Cyber Vault (Navy)",
         "url": "https://nsarchive.gwu.edu/project/cyber-vault",
         "kind": "free-analysis"},
    ],
    "NCDOC-TF1020-NRT-RFS": [
        {"coverage": "Red team methodology (public NIST)",
         "title": "NIST SP 800-115 — Technical Guide to Information Security Testing",
         "url": "https://csrc.nist.gov/pubs/sp/800/115/final",
         "kind": "free-pdf"},
        {"coverage": "DoD red team conceptual doctrine",
         "title": "USCYBERCOM public strategy documents",
         "url": "https://www.cybercom.mil/",
         "kind": "free-docs"},
        {"coverage": "Red/Blue team academic treatment",
         "title": "MITRE ATT&CK — Adversary Emulation Plans (free)",
         "url": "https://attack.mitre.org/resources/adversary-emulation-plans/",
         "kind": "free-framework"},
    ],
    "NTTP-3-13.1": [
        {"coverage": "Parent IO doctrine (public)",
         "title": "JP 3-13 — Information Operations",
         "url": "https://irp.fas.org/doddir/dod/jp3_13.pdf",
         "kind": "free-pdf-mirror",
         "note": "JP 3-13 is the parent public doctrine. NTTP 3-13.1 applies its IO planning to theater/campaign levels for the Navy."},
        {"coverage": "NATO strategic communications",
         "title": "NATO StratCom CoE — Publications",
         "url": "https://stratcomcoe.org/publications",
         "kind": "free-docs"},
        {"coverage": "US Army IO field manual (public)",
         "title": "FM 3-13 — Information Operations",
         "url": "https://armypubs.army.mil/",
         "kind": "free-docs"},
    ],
    "NTTP-3-13.2": [
        {"coverage": "Parent IO doctrine",
         "title": "JP 3-13 — Information Operations",
         "url": "https://irp.fas.org/doddir/dod/jp3_13.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "NAVIFOR public strategy",
         "title": "Naval Information Forces (NAVIFOR) public page",
         "url": "https://www.navifor.usff.navy.mil/",
         "kind": "free-docs"},
    ],
    "NWP-3-12": [
        {"coverage": "Parent joint doctrine (public 2018 edition)",
         "title": "JP 3-12 — Joint Cyberspace Operations",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror",
         "note": "NWP 3-12 directly parallels JP 3-12 with Navy implementation details. The JP 3-12 public version is the best single substitute."},
        {"coverage": "Air Force parallel doctrine (public)",
         "title": "AFDP 3-12 — Air Force Doctrine Publication: Cyberspace Operations",
         "url": "https://www.doctrine.af.mil/Portals/61/documents/AFDP_3-12/3-12-AFDP-CYBERSPACE-OPS.pdf",
         "kind": "free-pdf"},
        {"coverage": "NATO allied doctrine",
         "title": "NATO AJP-3.20 — Allied Joint Doctrine for Cyberspace Operations",
         "url": "https://assets.publishing.service.gov.uk/media/5f086ec4d3bf7f2bef137675/doctrine_nato_cyberspace_operations_ajp_3_20_1_.pdf",
         "kind": "free-pdf"},
        {"coverage": "Army War College strategic summary",
         "title": "Strategic Cyberspace Operations Guide (Army War College)",
         "url": "https://media.defense.gov/2023/Oct/02/2003312499/-1/-1/0/STRATEGIC_CYBERSPACE_OPERATIONS_GUIDE.PDF",
         "kind": "free-pdf"},
    ],
    "OPTASK-CYBERSPACE-OPS": [
        {"coverage": "Parent joint doctrine",
         "title": "JP 3-12 — Joint Cyberspace Operations",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "USCYBERCOM / NAVIFOR public statements",
         "title": "NAVIFOR — public operational guidance",
         "url": "https://www.navifor.usff.navy.mil/",
         "kind": "free-docs"},
    ],
    "USCC-INST-3000.14A": [
        {"coverage": "Deconfliction concept in public doctrine",
         "title": "JP 3-12 Chapter IV — Planning, Execution, Assessment",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror",
         "note": "JP 3-12 Chapter IV publicly describes the deconfliction process USCC INST 3000.14A formalizes."},
        {"coverage": "USCYBERCOM public strategy",
         "title": "USCYBERCOM — public strategy and vision documents",
         "url": "https://www.cybercom.mil/",
         "kind": "free-docs"},
    ],
    "USCYBERCOM-GENADMIN-22-0120": [
        {"coverage": "USCYBERCOM public structure (parent context)",
         "title": "JP 3-12 Chapter III — Authorities, Roles, Responsibilities",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror"},
        {"coverage": "USCYBERCOM public homepage",
         "title": "USCYBERCOM — mission and organization",
         "url": "https://www.cybercom.mil/About/",
         "kind": "free-docs"},
    ],
    "USSID-18": [
        {"coverage": "Declassified redacted version — NSA official public release",
         "title": "USSID 18 (Redacted) — NSA official release after Snowden disclosures",
         "url": "https://www.nsa.gov/portals/75/documents/news-features/press-room/statements/Snowden-USSID-18-Redacted.pdf",
         "kind": "free-pdf",
         "note": "NSA publicly released a redacted version after FOIA pressure. Covers Section 4 (the Bib's study scope) substantively. This IS the source you study from — the classified version is just this plus the redacted parts."},
        {"coverage": "EFF archive (same declassified doc)",
         "title": "USSID SP0018 — EFF archive (Jan 25 2011 edition)",
         "url": "https://www.eff.org/files/2013/11/21/20131119-odni-united_states_signals_intelligence_directive_18_jan_25_2011.pdf",
         "kind": "free-pdf"},
        {"coverage": "ACLU archive (earlier 1993 edition)",
         "title": "USSID 18 — ACLU archive (1993 version, NSA Release Nov 2013)",
         "url": "https://www.aclu.org/sites/default/files/field_document/1993-07-27_USSID-18_NSA-Release-November-2013.pdf",
         "kind": "free-pdf"},
        {"coverage": "Academic analysis of USSID 18",
         "title": "NSA Civil Liberties and Privacy Office — Review of Minimization Procedures",
         "url": "https://media.defense.gov/2021/Aug/18/2002833866/-1/-1/0/20171011-NSA-CLPO-DISSEMINATION-REPORT.PDF",
         "kind": "free-pdf",
         "note": "Official NSA CLPO review of minimization procedures under USSID 18. Helpful context for exam questions on US-person protections."},
    ],

    # ========================================================================
    # Deployable Security Trainer + remaining needs-user (1 non-book, non-JCAC)
    # ========================================================================
    "DEPLOYABLE-SEC-TRAINER": [
        {"coverage": "DISA cyber awareness / IA training (free, CAC-free mirrors)",
         "title": "DoD Cyber Awareness Challenge — public release",
         "url": "https://public.cyber.mil/training/cyber-awareness-challenge/",
         "kind": "free-course",
         "note": "DoD Cyber Exchange hosts current-year awareness and IA training; many modules are equivalent to the DST content."},
        {"coverage": "CDSE free catalog (security training)",
         "title": "Center for Development of Security Excellence (CDSE) — Free eLearning",
         "url": "https://www.cdse.edu/Training/eLearning/",
         "kind": "free-course",
         "note": "CDSE offers dozens of free security/IA courses covering the same material typically in a Deployable Security Trainer."},
        {"coverage": "DISA Information Assurance training",
         "title": "DoD Cyber Exchange — IA Training Catalog",
         "url": "https://public.cyber.mil/training/",
         "kind": "free-docs"},
    ],

    # ========================================================================
    # JCAC (10) — liberal free equivalents per the user's directive
    # ========================================================================
    "JCAC-ACTIVE-EXPLOIT": [
        {"coverage": "Pen test methodology (authoritative NIST)",
         "title": "NIST SP 800-115 — Technical Guide to Information Security Testing",
         "url": "https://csrc.nist.gov/pubs/sp/800/115/final",
         "kind": "free-pdf"},
        {"coverage": "MITRE ATT&CK — attack techniques and emulation",
         "title": "MITRE ATT&CK Matrix (Enterprise)",
         "url": "https://attack.mitre.org/matrices/enterprise/",
         "kind": "free-framework"},
        {"coverage": "Nmap official docs (the tool JCAC emphasizes)",
         "title": "Nmap Reference Guide (free)",
         "url": "https://nmap.org/book/man.html",
         "kind": "free-docs"},
        {"coverage": "PortSwigger free Web Security Academy",
         "title": "PortSwigger — Web Security Academy",
         "url": "https://portswigger.net/web-security",
         "kind": "free-course",
         "note": "Free hands-on labs covering the same attack techniques JCAC teaches for web targets."},
        {"coverage": "TryHackMe free paths",
         "title": "TryHackMe — Pre-Security + Jr Penetration Tester (free tiers)",
         "url": "https://tryhackme.com/",
         "kind": "free-course"},
    ],
    "JCAC-COMP-ORG-ARCH": [
        {"coverage": "x86-64 assembly + architecture (exact match for JCAC COA)",
         "title": "OpenSecurityTraining2 — Architecture 1001: x86-64 Assembly",
         "url": "https://p.ost2.fyi/courses/course-v1:OpenSecurityTraining2+Arch1001_x86-64_Asm+2021_v1/about",
         "kind": "free-course"},
        {"coverage": "OS-level architecture (follow-on)",
         "title": "OpenSecurityTraining2 — Architecture 2001: x86-64 OS Internals",
         "url": "https://beta.ost2.fyi/courses/course-v1:OpenSecurityTraining2+Arch2001_x86-64_OS_Internals+2022_v1_jc/about",
         "kind": "free-course"},
        {"coverage": "x86-64 architecture specification (authoritative)",
         "title": "Intel 64 and IA-32 Software Developer Manual Vol 1",
         "url": "https://cdrdv2-public.intel.com/671436/253665-sdm-vol-1.pdf",
         "kind": "free-pdf"},
        {"coverage": "Free computer organization textbook",
         "title": "Bryant + O'Hallaron — Computer Systems: A Programmer's Perspective (CMU free course materials)",
         "url": "https://csapp.cs.cmu.edu/",
         "kind": "free-docs"},
    ],
    "JCAC-FORENSIC-MAL": [
        {"coverage": "Malware analysis / RE fundamentals",
         "title": "MalwareUnicorn — Reverse Engineering 101",
         "url": "https://malwareunicorn.org/workshops/re101.html",
         "kind": "free-course"},
        {"coverage": "Memory forensics tool (authoritative)",
         "title": "Volatility Foundation — Framework Documentation",
         "url": "https://volatilityfoundation.org/the-volatility-framework/",
         "kind": "free-docs"},
        {"coverage": "SANS DFIR free posters",
         "title": "SANS DFIR — Memory Forensics Poster",
         "url": "https://www.sans.org/posters/dfir-memory-forensics",
         "kind": "free-poster"},
        {"coverage": "REMnux malware analysis Linux distro",
         "title": "REMnux — A Linux Toolkit for Malware Analysts",
         "url": "https://remnux.org/",
         "kind": "free-tool"},
        {"coverage": "Free textbook with CC license",
         "title": "Dennis Yurichev — Reverse Engineering for Beginners",
         "url": "https://beginners.re/",
         "kind": "free-pdf"},
    ],
    "JCAC-NETWORKING": [
        {"coverage": "Free CCNA-equivalent networking course",
         "title": "Cisco Networking Academy — Introduction to Networks",
         "url": "https://www.netacad.com/courses/networking/ccna-introduction-networks",
         "kind": "free-course"},
        {"coverage": "TCP/IP reference (authoritative)",
         "title": "The TCP/IP Guide (Kozierok) — free online version",
         "url": "http://www.tcpipguide.com/free/",
         "kind": "free-docs",
         "note": "Also on this Bib as BOOK-TCPIP-GUIDE."},
        {"coverage": "RFC 4291 — IPv6 addressing",
         "title": "RFC 4291 — IPv6 Addressing Architecture",
         "url": "https://www.rfc-editor.org/rfc/rfc4291",
         "kind": "rfc"},
        {"coverage": "RFC 4861 — IPv6 Neighbor Discovery",
         "title": "RFC 4861 — Neighbor Discovery for IPv6",
         "url": "https://www.rfc-editor.org/rfc/rfc4861",
         "kind": "rfc"},
        {"coverage": "Beej's free network programming guide",
         "title": "Beej's Guide to Network Programming",
         "url": "https://beej.us/guide/bgnet/",
         "kind": "free-docs"},
    ],
    "JCAC-OS": [
        {"coverage": "x86-64 OS internals (hands-on free course)",
         "title": "OpenSecurityTraining2 — Architecture 2001: x86-64 OS Internals",
         "url": "https://beta.ost2.fyi/courses/course-v1:OpenSecurityTraining2+Arch2001_x86-64_OS_Internals+2022_v1_jc/about",
         "kind": "free-course"},
        {"coverage": "MIT OCW — Operating System Engineering",
         "title": "MIT 6.828 / 6.S081 Operating System Engineering (OCW)",
         "url": "https://pdos.csail.mit.edu/6.828/",
         "kind": "free-course"},
        {"coverage": "Free OS textbook",
         "title": "Remzi Arpaci-Dusseau — Operating Systems: Three Easy Pieces (free)",
         "url": "https://pages.cs.wisc.edu/~remzi/OSTEP/",
         "kind": "free-pdf"},
        {"coverage": "Also on this Bib as BOOK-OS-CONCEPTS",
         "title": "Silberschatz — Operating System Concepts",
         "url": "#references/BOOK-OS-CONCEPTS",
         "kind": "cross-ref"},
    ],
    "JCAC-PROG-SCRIPT": [
        {"coverage": "Python tutorial (authoritative)",
         "title": "Python Official Tutorial",
         "url": "https://docs.python.org/3/tutorial/",
         "kind": "free-docs"},
        {"coverage": "Also on this Bib — Python for admin scripting",
         "title": "Automate the Boring Stuff with Python (on Bib)",
         "url": "#references/BOOK-AUTOMATE-PY",
         "kind": "cross-ref"},
        {"coverage": "Bash scripting guide",
         "title": "Advanced Bash-Scripting Guide (TLDP, free)",
         "url": "https://tldp.org/LDP/abs/html/",
         "kind": "free-docs"},
        {"coverage": "POSIX regex reference (JCAC study topic)",
         "title": "POSIX regex specification",
         "url": "https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html",
         "kind": "free-docs"},
    ],
    "JCAC-PROG-FUND": [
        {"coverage": "Harvard CS50 — Introduction to Computer Science (free)",
         "title": "Harvard CS50x on edX",
         "url": "https://cs50.harvard.edu/x/",
         "kind": "free-course"},
        {"coverage": "MIT OCW — Introduction to Computer Science and Programming",
         "title": "MIT 6.0001 — Intro to CS and Programming in Python (OCW)",
         "url": "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/",
         "kind": "free-course"},
        {"coverage": "Structure and Interpretation of Computer Programs (free)",
         "title": "SICP — full text online",
         "url": "https://sarabander.github.io/sicp/",
         "kind": "free-pdf"},
        {"coverage": "Data structures fundamentals",
         "title": "Princeton — Algorithms (free Coursera)",
         "url": "https://www.coursera.org/learn/algorithms-part1",
         "kind": "free-course"},
    ],
    "JCAC-PROTOCOL-ANALYSIS": [
        {"coverage": "Wireshark University free content",
         "title": "Wireshark — Documentation and Sample Captures",
         "url": "https://www.wireshark.org/docs/",
         "kind": "free-docs"},
        {"coverage": "Protocol reference — TCP/IP Guide (free online)",
         "title": "The TCP/IP Guide — free online edition",
         "url": "http://www.tcpipguide.com/free/",
         "kind": "free-docs"},
        {"coverage": "ICMP / IP protocol references",
         "title": "RFC 792 — Internet Control Message Protocol",
         "url": "https://www.rfc-editor.org/rfc/rfc792",
         "kind": "rfc"},
        {"coverage": "SNMP reference",
         "title": "RFC 3410 — SNMP framework overview",
         "url": "https://www.rfc-editor.org/rfc/rfc3410",
         "kind": "rfc"},
        {"coverage": "PCAP tutorials and sample captures",
         "title": "NETRESEC — PCAP Files Repository",
         "url": "https://www.netresec.com/?page=PcapFiles",
         "kind": "free-docs"},
    ],
    "JCAC-UNIX-LINUX": [
        {"coverage": "Free Linux textbook",
         "title": "The Linux Command Line (Shotts) — free full text",
         "url": "https://linuxcommand.org/tlcl.php",
         "kind": "free-pdf"},
        {"coverage": "Ryan's Tutorials — hands-on intro",
         "title": "Ryan's Tutorials — Linux",
         "url": "https://ryanstutorials.net/linuxtutorial/",
         "kind": "free-docs"},
        {"coverage": "Linux From Scratch (deep architecture)",
         "title": "Linux From Scratch Project",
         "url": "https://www.linuxfromscratch.org/lfs/",
         "kind": "free-docs"},
        {"coverage": "SUID/GUID + permissions reference",
         "title": "Linux Security Module / permissions docs",
         "url": "https://www.kernel.org/doc/html/latest/",
         "kind": "free-docs"},
        {"coverage": "OverTheWire — hands-on Linux wargames",
         "title": "OverTheWire — Bandit (free shell practice)",
         "url": "https://overthewire.org/wargames/bandit/",
         "kind": "free-course"},
    ],
    "JCAC-WINDOWS": [
        {"coverage": "Windows Internals — free authoritative docs",
         "title": "Microsoft Learn — Windows Internals",
         "url": "https://learn.microsoft.com/en-us/windows/win32/sysinfo/windows-internals",
         "kind": "free-docs"},
        {"coverage": "Memory protection / security mechanisms",
         "title": "Microsoft Learn — Process Mitigation Policies (DEP, ASLR, CFG)",
         "url": "https://learn.microsoft.com/en-us/windows/win32/procthread/process-mitigation-policies",
         "kind": "free-docs"},
        {"coverage": "Also on this Bib as BOOK-WIN-INTERNALS-1 / 2",
         "title": "Windows Internals Part 1 and Part 2 (on Bib)",
         "url": "#references/BOOK-WIN-INTERNALS-1",
         "kind": "cross-ref"},
        {"coverage": "Sysinternals toolkit (deep Windows diagnostics)",
         "title": "Sysinternals — Process Explorer, Autoruns, etc.",
         "url": "https://learn.microsoft.com/en-us/sysinternals/",
         "kind": "free-tool"},
        {"coverage": "Windows networking protocols reference",
         "title": "Microsoft — Windows Networking protocol docs",
         "url": "https://learn.microsoft.com/en-us/windows/win32/winsock/",
         "kind": "free-docs"},
    ],

    # ========================================================================
    # CLASSIFIED (3) — can't source content; just document the fact clearly
    # ========================================================================
    "USSID-104": [
        {"coverage": "Classified — name/number only, no public content available",
         "title": "USSID 104 is classified (typically TS//SI)",
         "url": "#",
         "kind": "classified-only",
         "note": "No adjacent public source exists for USSID 104 content. Study JP 3-12 + USSID 18 (public redacted) for the surrounding policy framework. For actual content, access is via official channels on appropriate classified networks only."},
        {"coverage": "Adjacent public doctrine (CNE context)",
         "title": "JP 3-12 Chapter II — OCO and cyberspace attack types",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror"},
    ],
    "USSID-6000": [
        {"coverage": "Classified — name/number only, no public content available",
         "title": "USSID 6000 is classified (NSA/USCC SIGINT activities)",
         "url": "#",
         "kind": "classified-only",
         "note": "No adjacent public source. Access via official channels only."},
        {"coverage": "Adjacent public context — USCYBERCOM public structure",
         "title": "JP 3-12 Chapter III — Authorities and relationships",
         "url": "https://irp.fas.org/doddir/dod/jp3_12.pdf",
         "kind": "free-pdf-mirror"},
    ],
    "CRITIC-HANDBOOK": [
        {"coverage": "Classified — name/number only",
         "title": "CRITIC Handbook is classified",
         "url": "#",
         "kind": "classified-only",
         "note": "CRITIC (Critical Information) reporting procedures. No public version. Access via official channels only."},
    ],
}


def main() -> int:
    data = json.loads(BIB.read_text(encoding="utf-8"))
    added_total = 0
    refs_touched = 0

    # Update sourceUrl on public-missing refs to point at FAS/mirror URLs
    sourceUrl_updates = {
        "JP-2-01":  "https://irp.fas.org/doddir/dod/jp2_01.pdf",
        "JP-3-0":   "https://irp.fas.org/doddir/dod/jp3_0.pdf",
        "JP-3-09":  "https://irp.fas.org/doddir/dod/jp3_09.pdf",
        "JP-3-12":  "https://irp.fas.org/doddir/dod/jp3_12.pdf",
        "JP-3-13":  "https://irp.fas.org/doddir/dod/jp3_13.pdf",
        "JP-3-25":  "https://irp.fas.org/doddir/dod/jp3_25.pdf",
        "JP-3-60":  "https://irp.fas.org/doddir/dod/jp3_60.pdf",
        "JP-5-0":   "https://irp.fas.org/doddir/dod/jp5_0.pdf",
        "DODM-5105.21-V1": "https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodm/510521m_vol1.PDF",
    }

    for ref in data["references"]:
        rid = ref["id"]
        if rid in ALTS:
            ref["alternatives"] = ALTS[rid]
            added_total += len(ALTS[rid])
            refs_touched += 1
        if rid in sourceUrl_updates:
            ref["sourceUrl"] = sourceUrl_updates[rid]

    BIB.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"Refs touched:         {refs_touched}")
    print(f"Alt sources added:    {added_total}")

    # Final summary
    total_refs = len(data["references"])
    refs_with_alts = sum(1 for r in data["references"] if r.get("alternatives"))
    refs_with_pdf  = sum(1 for r in data["references"] if r.get("availability") == "public-downloaded")
    refs_zero_src  = sum(1 for r in data["references"]
                         if not r.get("alternatives") and r.get("availability") != "public-downloaded")
    print()
    print(f"Bib total:                  {total_refs}")
    print(f"With downloaded PDF:        {refs_with_pdf}")
    print(f"With alternatives array:    {refs_with_alts}")
    print(f"With at least one source:   {refs_with_pdf + refs_with_alts - sum(1 for r in data['references'] if r.get('alternatives') and r.get('availability')=='public-downloaded')}")
    print(f"Completely unsourced:       {refs_zero_src}")
    if refs_zero_src:
        print("\nStill unsourced:")
        for r in data["references"]:
            if not r.get("alternatives") and r.get("availability") != "public-downloaded":
                print(f"  - {r['id']:<28}  {r.get('availability')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
